# Generated by Django 4.2.7 on 2023-11-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
