# Generated by Django 4.2.7 on 2023-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_alter_medicamento_precio_alter_venta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
