# Generated by Django 4.2.7 on 2023-11-20 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_venta_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
